# Generated by Django 5.0.1 on 2024-03-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='desc',
            field=models.CharField(max_length=500),
        ),
    ]
